#ifndef __COMMANDS_H
#define __COMMANDS_H

enum COMMAND {
  CMD_CONFIG_SINE_STEP = 'S',
  CMD_CONFIG_SINE_UPDATE_MAX = 'U',
  CMD_CONFIG_SINE_UPDATE_MIN = 'u',
  CMD_MOTOR_DISABLE = 'D',
  CMD_MOTOR_ENABLE = 'E',
  CMD_MOTOR_SPEED_RIGHT = 'R',
  CMD_MOTOR_SPEED_LEFT = 'L',
};


#endif